# Generated by Django 4.0.3 on 2022-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_alarm_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='blue',
            field=models.IntegerField(blank=True, default=235),
        ),
        migrations.AddField(
            model_name='alarm',
            name='green',
            field=models.IntegerField(blank=True, default=158),
        ),
        migrations.AddField(
            model_name='alarm',
            name='red',
            field=models.IntegerField(blank=True, default=52),
        ),
    ]
