# Generated by Django 4.0.3 on 2022-04-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alarm_blue_alarm_green_alarm_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='blue',
            field=models.IntegerField(default=235),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='green',
            field=models.IntegerField(default=158),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='red',
            field=models.IntegerField(default=52),
        ),
    ]
