# Generated by Django 4.0.3 on 2022-04-15 18:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_alarm_blue_alter_alarm_green_alter_alarm_red'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='blue',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='green',
        ),
        migrations.RemoveField(
            model_name='alarm',
            name='red',
        ),
        migrations.AddField(
            model_name='alarm',
            name='color',
            field=colorfield.fields.ColorField(default='#52E8FF', image_field=None, max_length=18, samples=None),
        ),
    ]
