# Generated by Django 4.0.3 on 2022-04-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_alarm_blue_remove_alarm_green_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.TimeField(db_index=True, unique=True),
        ),
    ]
