# Generated by Django 4.0.3 on 2022-04-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_alarm_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.TimeField(db_index=True),
        ),
    ]
